import { OperationPlanList } from '@/components/operation-plan'
import { operationPlanFixtures } from '@/lib/operation-plan/mock-data'

export default function OperationPlanPage() {
  return (
    <div className="space-y-6">
      <div className="space-y-2">
        <h1 className="text-2xl font-semibold tracking-tight">
          Operation plans
        </h1>
        <p className="text-muted-foreground text-sm">
          Review and approve plans generated by Copilot before executing cluster
          changes.
        </p>
      </div>
      <OperationPlanList plans={operationPlanFixtures} />
    </div>
  )
}
